import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { LayoutDocumentSchema, type Paragraph, type TextRun } from "@/schema";
import { textContent } from "@/lib/layout/text";
import { buildModel } from "./model";
import { mapToLayoutDocument, PUBLISHER_DEFAULT_LINE_SPACING } from "./mapper";
import { parseTrace } from "./trace-parser";

/**
 * Real-corpus goldens (plan §10.6): traces from four real store .pub files
 * (fixtures/pub-corpus/), generated by pub2raw inside this repo's toolchain.
 * These pin the quirks the synthetic golden couldn't know:
 *   - fo:font-size prints in INCHES (0.1667in = 12pt), not points
 *   - librevenge:rotate passes through unchanged (CW, about the center) —
 *     verified against pub2xhtml's reference render
 *   - explicit insertSpace callbacks carry word spacing
 *   - whitespace-only/empty trailing spans are styling noise
 *   - master-page-only publications convert empty (upstream limitation)
 * P2 additions: per-run styling (the labels' white ink), the §10.5 remap
 * tiers on real corpus families, Wingdings glyph translation, and the 128
 * checkpoint-label vector shapes converting as real paths.
 */

const load = (name: string) =>
  readFileSync(join(process.cwd(), "fixtures", "pub-traces", `${name}.trace`), "utf8");

const convert = (name: string) => mapToLayoutDocument(buildModel(parseTrace(load(name))), name);

const allRuns = (paragraphs: Paragraph[]): TextRun[] => paragraphs.flatMap((p) => p.runs);

describe("corpus: 3up_tabs.pub (binder-tab template, rotated text)", () => {
  const { doc, fonts, notes } = convert("3up_tabs");

  it("is a valid 3-page 9×11 document", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(3);
    expect(doc.size).toEqual({ w: 9, h: 11 });
    expect(doc.orientation).toBe("portrait");
  });

  it("places each tab label exactly, rotated 90° clockwise", () => {
    const tab1 = doc.pages[0].objects[0];
    if (tab1.type !== "text" || !tab1.text) throw new Error("expected text frame");
    expect(tab1.x).toBe(7.1455);
    expect(tab1.y).toBe(1.9828);
    expect(tab1.w).toBe(3.0939);
    expect(tab1.rotation).toBe(90); // passthrough — the pub2xhtml-verified sign
    expect(textContent(tab1.text)).toBe("Tab 1");
    expect(tab1.text.paragraphs[0].align).toBe("center");
  });

  it("converts inch-denominated font sizes to points", () => {
    const tab1 = doc.pages[0].objects[0];
    const tab3 = doc.pages[2].objects[0];
    if (tab1.type !== "text" || !tab1.text || tab3.type !== "text" || !tab3.text) throw new Error("text");
    expect(tab1.text.paragraphs[0].runs[0].font.size).toBe(12); // 0.1667in × 72
    expect(tab3.text.paragraphs[0].runs[0].font.size).toBe(10); // 0.1389in × 72
    expect(tab1.text.paragraphs[0].lineSpacing).toBe(PUBLISHER_DEFAULT_LINE_SPACING);
  });

  it("keeps Calibri as Calibri — the Carlito webfont stands in (§10.5 tier 1)", () => {
    const calibri = fonts.find((f) => f.source === "Calibri");
    expect(calibri?.mappedTo).toBe("Calibri");
    expect(calibri?.reason).toContain("Carlito");
    const tab1 = doc.pages[0].objects[0];
    if (tab1.type !== "text" || !tab1.text) throw new Error("text");
    expect(tab1.text.paragraphs[0].runs[0].font.family).toBe("Calibri");
  });

  it("carries the middle vertical alignment and default insets faithfully (P2)", () => {
    const tab1 = doc.pages[0].objects[0];
    if (tab1.type !== "text" || !tab1.text) throw new Error("text");
    expect(tab1.text.vAlign).toBe("middle");
    expect(tab1.text.inset).toEqual({ l: 0.04, r: 0.04, t: 0.04, b: 0.04 });
    // faithful now — neither warrants a note
    expect(notes.some((n) => n.message.includes("vertical alignment"))).toBe(false);
    expect(notes.some((n) => n.message.includes("insets"))).toBe(false);
  });
});

describe("corpus: bcim_double_cut.pub (2-sided business card with content)", () => {
  const { doc, fonts, fidelity } = convert("bcim_double_cut");

  it("is a valid 2-page 3.75×2.125 landscape document", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(2);
    expect(doc.size).toEqual({ w: 3.75, h: 2.125 });
    expect(doc.orientation).toBe("landscape");
  });

  it("carries the card copy with its geometry and per-run style", () => {
    const firstText = doc.pages[0].objects.find((o) => o.type === "text");
    if (!firstText || firstText.type !== "text" || !firstText.text) throw new Error("text");
    expect(textContent(firstText.text)).toContain("3 Peckville Road");
    expect(firstText.text.paragraphs[0].align).toBe("right");
    expect(allRuns(firstText.text.paragraphs).some((r) => r.font.size === 10)).toBe(true);
  });

  it("keeps Goudy Old Style by name — Sorts Mill Goudy stands in (§10.5 tier 2)", () => {
    const goudy = fonts.find((f) => f.source === "Goudy Old Style");
    expect(goudy?.mappedTo).toBe("Goudy Old Style");
    expect(goudy?.reason).toContain("Sorts Mill Goudy");
  });

  it("extracts the single JPEG bitmap fill to one picture frame (P3)", () => {
    const pictures = doc.pages.flatMap((p) => p.objects).filter((o) => o.type === "picture");
    expect(pictures).toHaveLength(1);
    const pic = pictures[0];
    if (pic.type !== "picture") throw new Error("picture");
    expect(pic.assetId).toBeDefined();
    expect(pic.fit).toBe("stretch");
    expect(Object.keys(doc.assets)).toHaveLength(1);
    // sniffed as JPEG (the declared mime agrees here) — 600×434, ~983 KB
    const asset = doc.assets[pic.assetId!];
    expect(asset.mime).toBe("image/jpeg");
    expect(asset.width).toBe(600);
    expect(asset.height).toBe(434);
    // nothing degrades now that the fill converts
    expect(fidelity.degraded).toBe(0);
  });

  it("keeps every shape inside the page bounds (sanity on real geometry)", () => {
    for (const page of doc.pages) {
      for (const obj of page.objects) {
        if (obj.type === "line") continue;
        expect(obj.x).toBeGreaterThanOrEqual(-0.5);
        expect(obj.y).toBeGreaterThanOrEqual(-0.5);
        expect(obj.x + obj.w).toBeLessThanOrEqual(doc.size.w + 0.5);
        expect(obj.y + obj.h).toBeLessThanOrEqual(doc.size.h + 0.5);
      }
    }
  });
});

describe("corpus: production_checkpoint_labels.pub (layered, vector-heavy)", () => {
  const { doc, fidelity, fonts, notes } = convert("production_checkpoint_labels");
  const objects = doc.pages.flatMap((p) => p.objects);
  const texts = objects.filter((o) => o.type === "text");

  it("is a valid 2-page document carrying all 192 shapes", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(2);
    // 64 text + 112 path + 16 picture — nothing dropped (16 of the 128 vector
    // shapes were bitmap-fill rectangles, now extracted to picture frames).
    expect(objects).toHaveLength(192);
  });

  it("converts the 112 non-image vector shapes as REAL paths (P2) — no bbox fallback", () => {
    const paths = objects.filter((o) => o.type === "path");
    // 128 vector shapes minus the 16 bitmap-fill rectangles (now pictures) = 112
    expect(paths).toHaveLength(112);
    expect(notes.some((n) => n.message.includes("bounding box"))).toBe(false);
    // normalized segments stay in the unit box
    for (const p of paths.slice(0, 8)) {
      if (p.type !== "path" || !p.d) throw new Error("path");
      for (const seg of p.d) {
        if (seg.c === "Z") continue;
        expect(seg.x).toBeGreaterThanOrEqual(-0.001);
        expect(seg.x).toBeLessThanOrEqual(1.001);
        expect(seg.y).toBeGreaterThanOrEqual(-0.001);
        expect(seg.y).toBeLessThanOrEqual(1.001);
      }
    }
    expect(fidelity.converted).toBeGreaterThanOrEqual(112);
  });

  it("extracts the 16 bitmap fills to picture frames sharing ONE deduped asset (P3)", () => {
    const pictures = objects.filter((o) => o.type === "picture");
    expect(pictures).toHaveLength(16);
    // identical payload applied to 16 sibling label frames → a single asset
    const assetIds = new Set(pictures.map((p) => (p.type === "picture" ? p.assetId : undefined)));
    expect(assetIds.size).toBe(1);
    for (const p of pictures) {
      if (p.type !== "picture") throw new Error("picture");
      expect(p.assetId).toBeDefined();
      expect(p.fit).toBe("stretch");
    }
    expect(Object.keys(doc.assets)).toHaveLength(1);
    // the corpus PNG is 915×300 — sniffed mime + real dimensions defined
    const asset = Object.values(doc.assets)[0];
    expect(asset.mime).toBe("image/png");
    expect(asset.width).toBe(915);
    expect(asset.height).toBe(300);
    expect(asset.bytes).toBe(19875);
    // the degradation these used to produce is gone
    expect(notes.some((n) => n.message.includes("bitmap fill flattened"))).toBe(false);
  });

  it("tallies fidelity clean now that the bitmap fills convert (P3)", () => {
    // pinned to the live corpus: 176 clean + 16 bitmap fills, all now converted
    expect(fidelity).toEqual({ converted: 192, degraded: 0, flagged: 0 });
  });

  it("renders the labels' white ink per run — the corpus case that forced text color", () => {
    const white = texts.filter(
      (o) => o.type === "text" && o.text && allRuns(o.text.paragraphs).some((r) => r.color === "#ffffff"),
    );
    expect(white.length).toBeGreaterThan(0);
  });

  it("translates the Wingdings checkbox marks to ✔ and notes it once", () => {
    const checks = texts.filter(
      (o) => o.type === "text" && o.text && textContent(o.text).includes("✔"),
    );
    expect(checks.length).toBeGreaterThan(0);
    expect(notes.filter((n) => n.message.includes("Wingdings"))).toHaveLength(1);
  });

  it("remaps the HelveticaNeue LT Pro cuts to Libre Franklin (§10.5 tier 2)", () => {
    const helveticas = fonts.filter((f) => /HelveticaNeue/i.test(f.source));
    expect(helveticas.length).toBeGreaterThan(0);
    for (const f of helveticas) expect(f.mappedTo).toBe("Libre Franklin");
  });

  it("preserves explicit insertSpace word spacing inside runs", () => {
    const mounting = texts.find(
      (o) => o.type === "text" && o.text && textContent(o.text).includes("Mounting: 280"),
    );
    if (!mounting || mounting.type !== "text" || !mounting.text) throw new Error("expected label text");
    // "insertText ( )" + 3 × insertSpace + "Mounting: 280" — spacing intact
    expect(textContent(mounting.text)).toContain("    Mounting: 280");
  });

  it("carries the 125% line spacing where the source sets it", () => {
    const spaced = texts.find(
      (o) => o.type === "text" && o.text?.paragraphs.some((p) => p.lineSpacing === 1.25),
    );
    expect(spaced).toBeDefined();
  });

  it("notes the flattened source layers once", () => {
    expect(notes.filter((n) => n.message.includes("layers flattened"))).toHaveLength(1);
  });
});

describe("corpus: business_card_template_10up.pub (master-page-only template)", () => {
  const { doc, notes } = convert("business_card_template_10up");

  it("converts to a valid empty document — never a crash, never a fake win", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(1);
    expect(doc.pages[0].objects).toHaveLength(0);
  });

  it("flags the upstream master-page limitation as tier 3", () => {
    const flag = notes.find((n) => n.tier === 3 && n.message.includes("master pages"));
    expect(flag).toBeDefined();
  });
});
