import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { LayoutDocumentSchema } from "@/schema";
import { buildModel } from "./model";
import { mapToLayoutDocument, PUBLISHER_DEFAULT_LINE_SPACING } from "./mapper";
import { parseTrace } from "./trace-parser";

/**
 * Real-corpus goldens (plan §10.6): traces from four real store .pub files
 * (fixtures/pub-corpus/), generated by pub2raw inside this repo's toolchain.
 * These pin the quirks the synthetic golden couldn't know:
 *   - fo:font-size prints in INCHES (0.1667in = 12pt), not points
 *   - librevenge:rotate passes through unchanged (CW, about the center) —
 *     verified against pub2xhtml's reference render
 *   - explicit insertSpace callbacks carry word spacing
 *   - whitespace-only/empty trailing spans are styling noise
 *   - master-page-only publications convert empty (upstream limitation)
 */

const load = (name: string) =>
  readFileSync(join(process.cwd(), "fixtures", "pub-traces", `${name}.trace`), "utf8");

const convert = (name: string) => mapToLayoutDocument(buildModel(parseTrace(load(name))), name);

describe("corpus: 3up_tabs.pub (binder-tab template, rotated text)", () => {
  const { doc, fonts, notes } = convert("3up_tabs");

  it("is a valid 3-page 9×11 document", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(3);
    expect(doc.size).toEqual({ w: 9, h: 11 });
    expect(doc.orientation).toBe("portrait");
  });

  it("places each tab label exactly, rotated 90° clockwise", () => {
    const tab1 = doc.pages[0].objects[0];
    if (tab1.type !== "text" || !tab1.text) throw new Error("expected text frame");
    expect(tab1.x).toBe(7.1455);
    expect(tab1.y).toBe(1.9828);
    expect(tab1.w).toBe(3.0939);
    expect(tab1.rotation).toBe(90); // passthrough — the pub2xhtml-verified sign
    expect(tab1.text.content).toBe("Tab 1");
    expect(tab1.text.align).toBe("center");
  });

  it("converts inch-denominated font sizes to points", () => {
    const tab1 = doc.pages[0].objects[0];
    const tab3 = doc.pages[2].objects[0];
    if (tab1.type !== "text" || !tab1.text || tab3.type !== "text" || !tab3.text) throw new Error("text");
    expect(tab1.text.font.size).toBe(12); // 0.1667in × 72
    expect(tab3.text.font.size).toBe(10); // 0.1389in × 72
    expect(tab1.text.lineSpacing).toBe(PUBLISHER_DEFAULT_LINE_SPACING);
  });

  it("remaps Calibri (not yet in the curated list) with a named entry — Carlito lands in P2", () => {
    const calibri = fonts.find((f) => f.source === "Calibri");
    expect(calibri?.mappedTo).toBe("Motiva Sans");
    expect(calibri?.reason).toContain("P2");
  });

  it("notes the middle vertical alignment and insets — empty trailing spans don't fake a flatten", () => {
    const msgs = notes.map((n) => n.message);
    expect(msgs.some((m) => m.includes("vertical alignment 'middle'"))).toBe(true);
    expect(msgs.some((m) => m.includes("insets"))).toBe(true);
    // each frame has one real span + one empty span — that's not multi-styling
    expect(msgs.some((m) => m.includes("character styles flattened"))).toBe(false);
  });
});

describe("corpus: bcim_double_cut.pub (2-sided business card with content)", () => {
  const { doc, fonts } = convert("bcim_double_cut");

  it("is a valid 2-page 3.75×2.125 landscape document", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(2);
    expect(doc.size).toEqual({ w: 3.75, h: 2.125 });
    expect(doc.orientation).toBe("landscape");
  });

  it("carries the card copy with its geometry", () => {
    const firstText = doc.pages[0].objects.find((o) => o.type === "text");
    if (!firstText || firstText.type !== "text" || !firstText.text) throw new Error("text");
    expect(firstText.text.content).toContain("3 Peckville Road");
    expect(firstText.text.align).toBe("right");
    expect(firstText.text.font.size).toBe(10);
  });

  it("remaps the unknown corpus font with a named report entry", () => {
    const goudy = fonts.find((f) => f.source === "Goudy Old Style");
    expect(goudy?.mappedTo).toBe("Motiva Sans");
    expect(goudy?.reason).toContain("P2");
  });

  it("keeps every shape inside the page bounds (sanity on real geometry)", () => {
    for (const page of doc.pages) {
      for (const obj of page.objects) {
        if (obj.type === "line") continue;
        expect(obj.x).toBeGreaterThanOrEqual(-0.5);
        expect(obj.y).toBeGreaterThanOrEqual(-0.5);
        expect(obj.x + obj.w).toBeLessThanOrEqual(doc.size.w + 0.5);
        expect(obj.y + obj.h).toBeLessThanOrEqual(doc.size.h + 0.5);
      }
    }
  });
});

describe("corpus: production_checkpoint_labels.pub (layered, vector-heavy)", () => {
  const { doc, fidelity, notes } = convert("production_checkpoint_labels");

  it("is a valid 2-page document carrying all 192 shapes", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(2);
    const total = doc.pages.reduce((n, p) => n + p.objects.length, 0);
    expect(total).toBe(192); // 64 text + 96 polygons + 32 paths — nothing dropped
  });

  it("degrades the 128 vector shapes to bounding boxes with notes, not silently", () => {
    const bboxNotes = notes.filter((n) => n.message.includes("bounding box"));
    expect(bboxNotes.length).toBe(128);
    expect(fidelity.degraded).toBeGreaterThanOrEqual(128);
  });

  it("preserves explicit insertSpace word spacing inside runs", () => {
    const texts = doc.pages.flatMap((p) => p.objects).filter((o) => o.type === "text");
    const mounting = texts.find((o) => o.type === "text" && o.text?.content.includes("Mounting: 280"));
    if (!mounting || mounting.type !== "text" || !mounting.text) throw new Error("expected label text");
    // "insertText ( )" + 3 × insertSpace + "Mounting: 280" — spacing intact
    expect(mounting.text.content).toContain("    Mounting: 280");
  });

  it("carries the 125% line spacing where the source sets it", () => {
    const spaced = doc.pages
      .flatMap((p) => p.objects)
      .find((o) => o.type === "text" && o.text?.lineSpacing === 1.25);
    expect(spaced).toBeDefined();
  });

  it("notes the flattened source layers once", () => {
    expect(notes.filter((n) => n.message.includes("layers flattened"))).toHaveLength(1);
  });
});

describe("corpus: business_card_template_10up.pub (master-page-only template)", () => {
  const { doc, notes } = convert("business_card_template_10up");

  it("converts to a valid empty document — never a crash, never a fake win", () => {
    expect(LayoutDocumentSchema.safeParse(doc).success).toBe(true);
    expect(doc.pages).toHaveLength(1);
    expect(doc.pages[0].objects).toHaveLength(0);
  });

  it("flags the upstream master-page limitation as tier 3", () => {
    const flag = notes.find((n) => n.tier === 3 && n.message.includes("master pages"));
    expect(flag).toBeDefined();
  });
});
